### ISSUE TITLE
Docker compose instructions

### ISSUE THREAD

**Issue by trip5** [Morcatko/EspHome-Editor#22]
A bit of errors with your sample docker `compose.yaml` - a `name` isn't required as far as I know but useful for some docker managers like Dokemon.  Also, the image needs to point to the `morcatko` user on Docker Hub.  You can disregard my other edits... except maybe esphome-editor-config ?  It wasn't too obvious it needs it's own config folder.  At first I added in my path to esphome config files and it was looking pretty weird...

```
name: esphome-editor
services:
    esphome-editor:
        image: morcatko/esphome-editor:latest
        container_name: esphome-editor
        environment:
            - ESPHOME_URL=http://__LOCALIP__:__PORT__/
        ports:
            - ___EDITORPORT__:3000
        volumes:
            - /path/to/esphome-editor-config/:/app/work-folder/devices
```

And again, it looks good!  Hoping to test it out a bit later!  (BTW sorry for opening 2 issues but I figured this one is an easy fix and can get closed pretty quick anyways.)
